variables:
  MAVEN_OPTS: >-
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

.validate: &validate
  stage: build
  script:
    - 'mvn test-compile'
  except:
    - gh-pages
  artifacts:
    untracked: true

.test: &test
  stage: test
  script:
    - 'mvn verify site site:stage'
  except:
    - gh-pages
  
validate:jdk7:
  <<: *validate
  image: mfriedenhagen/docker-maven:3.3.9-jdk-7

validate:jdk8:
  <<: *validate
  image: mfriedenhagen/docker-maven:3.3.9-jdk-8

test:jdk7:
  <<: *test
  image: mfriedenhagen/docker-maven:3.3.9-jdk-7

test:jdk8:
  <<: *test
  image: mfriedenhagen/docker-maven:3.3.9-jdk-8
  artifacts:
    paths:
      - target/staging/tljunit-parent/

pages:
  image: busybox:latest
  stage: deploy
  script:
    - mv target/staging/tljunit-parent/ public
  dependencies:
    - test:jdk8
  artifacts:
    paths:
    - public
  only:
    - master

