language: java
jdk:
  - oraclejdk7
  - oraclejdk8
install: "mvn --errors --batch-mode -P foss-parent-verification validate dependency:go-offline"
script: "mvn --errors --batch-mode -Dversions.skip=true -P foss-parent-verification clean verify site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
